-- ==============================================================================
-- SCHEMA DEFINITIVO - LIBRERÍA & POS (Admin + Web Pública)
-- ==============================================================================

-- 1. TABLA PRODUCTOS
CREATE TABLE IF NOT EXISTS public.productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    categoria TEXT NOT NULL,
    precio_costo NUMERIC(10, 2) DEFAULT 0,
    precio_venta NUMERIC(10, 2) NOT NULL,
    stock_actual INTEGER DEFAULT 0,
    stock_minimo INTEGER DEFAULT 5,
    sku TEXT UNIQUE,
    imagen_url TEXT,
    es_servicio BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABLA VENTAS
-- Actualizada para soportar pedidos web anónimos
CREATE TABLE IF NOT EXISTS public.ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    total NUMERIC(10, 2) NOT NULL,
    metodo_pago TEXT DEFAULT 'Efectivo',
    usuario_id UUID REFERENCES auth.users(id), -- Puede ser NULL para ventas web
    cliente_nombre TEXT,                   -- Nuevo: Para pedidos web
    cliente_telefono TEXT,                 -- Nuevo: Para contacto WhatsApp
    estado TEXT DEFAULT 'completado'       -- Nuevo: 'pendiente' (web) o 'completado' (local)
);

-- 3. TABLA DETALLE_VENTAS
CREATE TABLE IF NOT EXISTS public.detalle_ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT REFERENCES public.ventas(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES public.productos(id),
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL
);

-- =============================================
-- SEGURIDAD (RLS) - CONFIGURACIÓN HÍBRIDA
-- =============================================

ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_ventas ENABLE ROW LEVEL SECURITY;

-- A. POLÍTICAS DE PRODUCTOS
-- Todos pueden ver (Web y Admin)
CREATE POLICY "Productos visibles para todos" 
ON public.productos FOR SELECT 
TO public 
USING (true);

-- Solo Admin edita
CREATE POLICY "Admin gestiona productos" 
ON public.productos FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- B. POLÍTICAS DE VENTAS (La clave del éxito)
-- La Web (público) puede CREAR pedidos, pero no ver los de otros
CREATE POLICY "Web Publica Crea Ventas" 
ON public.ventas FOR INSERT 
TO public 
WITH CHECK (true);

-- El Admin tiene control total
CREATE POLICY "Admin Control Total Ventas" 
ON public.ventas FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- C. POLÍTICAS DE DETALLES
CREATE POLICY "Web Publica Crea Detalles" 
ON public.detalle_ventas FOR INSERT 
TO public 
WITH CHECK (true);

CREATE POLICY "Admin Control Total Detalles" 
ON public.detalle_ventas FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- =============================================
-- VISTAS Y FUNCIONES
-- =============================================

-- Vista segura para la web (sin precios de costo)
CREATE OR REPLACE VIEW public.catalogo_web AS
SELECT id, nombre, categoria, precio_venta as precio, stock_actual as stock, imagen_url, sku
FROM public.productos
WHERE stock_actual > 0 OR es_servicio = TRUE;

-- Función para descontar stock atómicamente
CREATE OR REPLACE FUNCTION descontar_stock(p_id bigint, p_cantidad int)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE public.productos
  SET stock_actual = stock_actual - p_cantidad
  WHERE id = p_id;
END;
$$;